server.port=9094
spring.datasource.url=jdbc:mysql://localhost:3306/wallet?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
user.onboarding.amount=10
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
